# -*- coding: utf-8 -*-
# developed by Behnam Mardani
# bmardani2@gmail.com
#
# Created by: PyQt5 UI code generator 5.15.2
#
# 
# Do not edit this file unless you know what you are doing.

'''
Click generate new one button to generate a new Sudoku table.

By clicking solve button the table will filled and current game is over.

Click hint button show you that wich input is incorrect in red color. 

'''






from PyQt5 import QtCore, QtGui, QtWidgets
from random import sample
import numpy as np

class Ui_sudoku(object):
    def setupUi(self, sudoku):
        sudoku.setObjectName("sudoku")
        sudoku.resize(659, 600)
        self.centralwidget = QtWidgets.QWidget(sudoku)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 10, 561, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(2, 20, 21, 441))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(540, 20, 71, 441))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 455, 561, 21))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(10, 160, 561, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_5.setFont(font)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 300, 561, 31))
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(182, 20, 31, 441))
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(355, 20, 61, 441))
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.solver = QtWidgets.QPushButton(self.centralwidget)
        self.solver.setGeometry(QtCore.QRect(200, 480, 181, 23))
        self.solver.setObjectName("solver")
        self._generator = QtWidgets.QPushButton(self.centralwidget)
        self._generator.setGeometry(QtCore.QRect(10, 480, 181, 23))
        self._generator.setObjectName("_generator")
        self.timer = QtWidgets.QLabel(self.centralwidget)
        self.timer.setGeometry(QtCore.QRect(390, 480, 181, 23))
        self.timer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timer.setText("")
        self.timer.setObjectName("timer")
        self.hinter = QtWidgets.QPushButton(self.centralwidget)
        self.hinter.setGeometry(QtCore.QRect(10, 510, 181, 23))
        self.hinter.setObjectName("check for incorrect input")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 181, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 2, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 2, 0, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 2, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 1, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 0, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 0, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 0, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 1, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(200, 20, 181, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_2.addWidget(self.lineEdit_36, 2, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_2.addWidget(self.lineEdit_34, 2, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_2.addWidget(self.lineEdit_35, 2, 1, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_2.addWidget(self.lineEdit_25, 1, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 0, 1, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_2.addWidget(self.lineEdit_24, 1, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 0, 0, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 0, 2, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_2.addWidget(self.lineEdit_26, 1, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(390, 20, 181, 141))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_3.addWidget(self.lineEdit_39, 2, 2, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_3.addWidget(self.lineEdit_37, 2, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_3.addWidget(self.lineEdit_38, 2, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_3.addWidget(self.lineEdit_28, 1, 1, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 0, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_3.addWidget(self.lineEdit_27, 1, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 0, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_3.addWidget(self.lineEdit_19, 0, 2, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_3.addWidget(self.lineEdit_29, 1, 2, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 181, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_4.addWidget(self.lineEdit_63, 2, 2, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout_4.addWidget(self.lineEdit_61, 2, 0, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_4.addWidget(self.lineEdit_62, 2, 1, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_4.addWidget(self.lineEdit_52, 1, 1, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_4.addWidget(self.lineEdit_42, 0, 1, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_4.addWidget(self.lineEdit_51, 1, 0, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_4.addWidget(self.lineEdit_41, 0, 0, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_4.addWidget(self.lineEdit_43, 0, 2, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_4.addWidget(self.lineEdit_53, 1, 2, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(200, 170, 181, 141))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout_5.addWidget(self.lineEdit_66, 2, 2, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout_5.addWidget(self.lineEdit_64, 2, 0, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout_5.addWidget(self.lineEdit_65, 2, 1, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_5.addWidget(self.lineEdit_55, 1, 1, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_5.addWidget(self.lineEdit_45, 0, 1, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_5.addWidget(self.lineEdit_54, 1, 0, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_5.addWidget(self.lineEdit_44, 0, 0, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_5.addWidget(self.lineEdit_46, 0, 2, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_5.addWidget(self.lineEdit_56, 1, 2, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(390, 170, 181, 141))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.gridLayout_6.addWidget(self.lineEdit_69, 2, 2, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout_6.addWidget(self.lineEdit_67, 2, 0, 1, 1)
        self.lineEdit_68 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.gridLayout_6.addWidget(self.lineEdit_68, 2, 1, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_6.addWidget(self.lineEdit_58, 1, 1, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_6.addWidget(self.lineEdit_48, 0, 1, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_6.addWidget(self.lineEdit_57, 1, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_6.addWidget(self.lineEdit_47, 0, 0, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_6.addWidget(self.lineEdit_49, 0, 2, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_6.addWidget(self.lineEdit_59, 1, 2, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 320, 181, 141))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lineEdit_93 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.gridLayout_7.addWidget(self.lineEdit_93, 2, 2, 1, 1)
        self.lineEdit_91 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.gridLayout_7.addWidget(self.lineEdit_91, 2, 0, 1, 1)
        self.lineEdit_92 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.gridLayout_7.addWidget(self.lineEdit_92, 2, 1, 1, 1)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.gridLayout_7.addWidget(self.lineEdit_82, 1, 1, 1, 1)
        self.lineEdit_72 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.gridLayout_7.addWidget(self.lineEdit_72, 0, 1, 1, 1)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.gridLayout_7.addWidget(self.lineEdit_81, 1, 0, 1, 1)
        self.lineEdit_71 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.gridLayout_7.addWidget(self.lineEdit_71, 0, 0, 1, 1)
        self.lineEdit_73 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.gridLayout_7.addWidget(self.lineEdit_73, 0, 2, 1, 1)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.gridLayout_7.addWidget(self.lineEdit_83, 1, 2, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(200, 320, 181, 141))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_96 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.gridLayout_8.addWidget(self.lineEdit_96, 2, 2, 1, 1)
        self.lineEdit_94 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.gridLayout_8.addWidget(self.lineEdit_94, 2, 0, 1, 1)
        self.lineEdit_95 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.gridLayout_8.addWidget(self.lineEdit_95, 2, 1, 1, 1)
        self.lineEdit_85 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.gridLayout_8.addWidget(self.lineEdit_85, 1, 1, 1, 1)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.gridLayout_8.addWidget(self.lineEdit_75, 0, 1, 1, 1)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.gridLayout_8.addWidget(self.lineEdit_84, 1, 0, 1, 1)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.gridLayout_8.addWidget(self.lineEdit_74, 0, 0, 1, 1)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.gridLayout_8.addWidget(self.lineEdit_76, 0, 2, 1, 1)
        self.lineEdit_86 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.gridLayout_8.addWidget(self.lineEdit_86, 1, 2, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(390, 320, 181, 141))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.lineEdit_99 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.gridLayout_9.addWidget(self.lineEdit_99, 2, 2, 1, 1)
        self.lineEdit_97 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.gridLayout_9.addWidget(self.lineEdit_97, 2, 0, 1, 1)
        self.lineEdit_98 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.gridLayout_9.addWidget(self.lineEdit_98, 2, 1, 1, 1)
        self.lineEdit_88 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.gridLayout_9.addWidget(self.lineEdit_88, 1, 1, 1, 1)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.gridLayout_9.addWidget(self.lineEdit_78, 0, 1, 1, 1)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.gridLayout_9.addWidget(self.lineEdit_87, 1, 0, 1, 1)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.gridLayout_9.addWidget(self.lineEdit_77, 0, 0, 1, 1)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.gridLayout_9.addWidget(self.lineEdit_79, 0, 2, 1, 1)
        self.lineEdit_89 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.gridLayout_9.addWidget(self.lineEdit_89, 1, 2, 1, 1)
        sudoku.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sudoku)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 659, 21))
        self.menubar.setObjectName("menubar")
        sudoku.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sudoku)
        self.statusbar.setObjectName("statusbar")
        sudoku.setStatusBar(self.statusbar)

        self.retranslateUi(sudoku)
        QtCore.QMetaObject.connectSlotsByName(sudoku)
        
        self.arr = [[self.lineEdit_11,self.lineEdit_12,self.lineEdit_13,self.lineEdit_14,self.lineEdit_15,self.lineEdit_16,self.lineEdit_17,self.lineEdit_18,self.lineEdit_19],
                    [self.lineEdit_21,self.lineEdit_22,self.lineEdit_23,self.lineEdit_24,self.lineEdit_25,self.lineEdit_26,self.lineEdit_27,self.lineEdit_28,self.lineEdit_29],
                    [self.lineEdit_31,self.lineEdit_32,self.lineEdit_33,self.lineEdit_34,self.lineEdit_35,self.lineEdit_36,self.lineEdit_37,self.lineEdit_38,self.lineEdit_39],
                    [self.lineEdit_41,self.lineEdit_42,self.lineEdit_43,self.lineEdit_44,self.lineEdit_45,self.lineEdit_46,self.lineEdit_47,self.lineEdit_48,self.lineEdit_49],
                    [self.lineEdit_51,self.lineEdit_52,self.lineEdit_53,self.lineEdit_54,self.lineEdit_55,self.lineEdit_56,self.lineEdit_57,self.lineEdit_58,self.lineEdit_59],
                    [self.lineEdit_61,self.lineEdit_62,self.lineEdit_63,self.lineEdit_64,self.lineEdit_65,self.lineEdit_66,self.lineEdit_67,self.lineEdit_68,self.lineEdit_69],
                    [self.lineEdit_71,self.lineEdit_72,self.lineEdit_73,self.lineEdit_74,self.lineEdit_75,self.lineEdit_76,self.lineEdit_77,self.lineEdit_78,self.lineEdit_79],
                    [self.lineEdit_81,self.lineEdit_82,self.lineEdit_83,self.lineEdit_84,self.lineEdit_85,self.lineEdit_86,self.lineEdit_87,self.lineEdit_88,self.lineEdit_89],
                    [self.lineEdit_91,self.lineEdit_92,self.lineEdit_93,self.lineEdit_94,self.lineEdit_95,self.lineEdit_96,self.lineEdit_97,self.lineEdit_98,self.lineEdit_99]]
        

    def retranslateUi(self, sudoku):
        _translate = QtCore.QCoreApplication.translate
        sudoku.setWindowTitle(_translate("sudoku", "sudoku game"))
        self.solver.setText(_translate("sudoku", "solve"))
        self._generator.setText(_translate("sudoku", "generate new one"))
        self.hinter.setText(_translate("sudoku", "hint"))

            
        self.solver.clicked.connect(self.solve_game)
        self.hinter.clicked.connect(self.show_number)
        self._generator.clicked.connect(self.create_new_game)
        self.hinter.clicked.connect(self.check_input)
        
    def solve_game(self):
        
        for i in range(0,9) :
            for j in range(0,9):
                self.arr[i][j].setText(str(self.final_board[i][j]))
                self.arr[i][j].setStyleSheet("color: green;")
        
    def show_number(self):
        pass
        
    def create_new_game(self):
        
        for i in range(0,9) :
            for j in range(0,9):
                self.arr[i][j].setText('')
        
        self.base  = 3
        self.side  = self.base*self.base
        
        rBase = range(self.base) 
        rows  = [ g*self.base + r for g in self.shuffle(rBase) for r in self.shuffle(rBase) ] 
        cols  = [ g*self.base + c for g in self.shuffle(rBase) for c in self.shuffle(rBase) ]
        nums  = self.shuffle(range(1,self.base*self.base+1))
       
        self.final_board = np.zeros((9,9),dtype='int16')
        self.board = np.zeros((9,9))
        for r in rows :
            for c in cols :
                temp = (self.base*(r%self.base)+r//self.base+c)%self.side
                self.board[r][c] = nums[temp]
        
        #self.final_board = str(board)
        for i in range(0,9):
            for j in range(0,9):
                self.final_board[i][j] = self.board[i][j]
        print(self.final_board)
        squares = self.side*self.side
        empties = squares * 3//4
        for p in sample(range(squares),empties):
            self.board[p//self.side][p%self.side] = 0
        
        
        
        for i in range(0,9):
            for j in range(0,9):
                if self.board[i][j] != 0 :
                    self.arr[i][j].setText(str(int(self.board[i][j])))
        
        
    

    def shuffle(k,s): 
    
        return sample(s,len(s)) 
        
    def check_input(self):
        for i in range(0,9) :
            for j in range(0,9):
                user_input = self.arr[i][j].text()
                if user_input != str(self.final_board[i][j]) and user_input != str(self.board[i][j]) :
                    self.arr[i][j].setStyleSheet("color: red;")
                    self.timer.setText("red input is incorrect")
                if user_input == "" :
                    self.arr[i][j].setStyleSheet("color: black;")
                
                

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sudoku = QtWidgets.QMainWindow()
    ui = Ui_sudoku()
    ui.setupUi(sudoku)
    sudoku.show()
    sys.exit(app.exec_())
